### ISSUE TITLE
翻阅星图时如果重氢不够可以切换星球

### ISSUE THREAD

**Issue by forestsheep** [forestsheep/OgameFarmer#7]
翻阅星图时如果重氢不够，可以切换星球。
可以在画面上设置选项，勾选中的情况下，可以不通知用户直接切换星球。

**Comment by AtkinsChang** [comment]
This api can check planet status without HH consumption  
I don't know hows it work, but 
XXXX/index.php?page=fleetcheck&ajax=1&galaxy=1&system=45&planet=10&type=2
can check debris, "11" for debris and "1d" for empty.

Maybe this may help

**Comment by forestsheep** [comment]
@AtkinsChang 
thank you.
it not work on sever which i playing.
i don't care HH consumption when paging star map.user maybe forget his current ball is moon without any HH on it.
whatever, this not important task,i'll do it later.
